### ISSUE TITLE
Empty sso window

### ISSUE THREAD

**Issue by Devil666face** [waelmas/frameless-bitb#8]
After entering your email, an automatic redirect to sso.domain.com occurs with an empty password window. I cleared my cookies and use a private window.
From this:
![2024-03-09_10-46](https://github.com/waelmas/frameless-bitb/assets/102591448/596e96d5-de6b-4b87-aa4c-09d3bf3af99a)
Just redirect to: 
![2024-03-09_10-47](https://github.com/waelmas/frameless-bitb/assets/102591448/c1796245-09e9-4c77-a4e1-9614b614a8ce)
With empty window
![2024-03-09_10-48](https://github.com/waelmas/frameless-bitb/assets/102591448/518cf516-9080-4726-bb70-df98db79d4c2)

**Comment by waelmas** [comment]
Hey there,

The reason you are seeing this is because you are using a gmail address which requires a very different setup even without the BITB addition this repo brings to the picture. The setup this repo explains and builds on top of is designed for Microsoft Enterprise accounts specifically.

Even with Evilginx alone, as far as I know Google is the most challenging to get a working phishlet for as it adds many security layers to protect against MiTM phishing.
